flaskblog_3/flask_webapp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    #title of the post:-->every post has to have a title
    title = StringField('Title',validators=[DataRequired()])
    #content of the post-->necessary
    content = TextAreaField('Content',validators=[DataRequired()])
    #submit button to post this to our route
    submit = SubmitField('Post')

flaskblog_3/flask_webapp/main/routes.py
#home and about blueprint
from flask import render_template, request, Blueprint
from flask_webapp.db_models import Post

main=Blueprint('main',__name__) #'users' is the blueprint name

@main.route("/")
@main.route("/home")
def home():
    #grab post from db
    # post = Post.query.all()-->older
    # pagination:
    #to get the requested page number from the url
    page = request.args.get('page',1,type=int)#default page no is 1 
    post = Post.query.order_by(Post.date_posted.desc()).paginate(page = page,per_page=5)
    return render_template('home.html',posts=post)#-->to create static html pages

# to write a code in html template we use code blocks like--> 
# {% for post in posts %}
#     {% endfor %}

@main.route("/about")
def about():
    return render_template('about.html',title='About')

flaskblog_3/flask_webapp/posts/routes.py
#posts blueprint
from flask import render_template, url_for, flash,redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_webapp import db
from flask_webapp.db_models import Post
from flask_webapp.posts.forms import PostForm

posts=Blueprint('posts',__name__) #'users' is the blueprint name

@posts.route("/post/new",methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm() 
    if form.validate_on_submit():
        # save posts to our db
        post = Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form,legend='New Post')


@posts.route("/post/<int:post_id>")# to add variable in our route-->use angular brackets
def post(post_id):
    #fetch the post if it exists
    # post = Post.query.get(post_id) OR 
    post = Post.query.get_or_404(post_id)#returns a 404 page if the post doesnt exist
    return render_template('post.html',title=post.title,post=post)

@posts.route("/post/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    #ensure that the user who wrote that post can only update the post
    if post.author != current_user:
        abort(403) #403 response is the http response for a forbidden route
    # if the user is the author then we create a form to update post and render template
    form = PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        #no need to add as it is already in the db
        db.session.commit()
        flash('Your post has been updated!','success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method=='GET':
        form.title.data=post.title
        form.content.data=post.content
    return render_template('create_post.html',title='Update Post',form=form,legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])# only post request when we are going to submit the modal
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog_3/flask_webapp/users/routes.py
#users blueprint
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_webapp import db, bcrypt
from flask_webapp.db_models import User, Post
from flask_webapp.users.forms import RegisterationForm, LoginForm, UpdateAccountForm,RequestResetForm, ResetPasswordForm
from flask_webapp.users.utils import save_picture, send_reset_email

users=Blueprint('users',__name__) #'users' is the blueprint name

#add routes-->specifically for the users blueprint instead of the global app variable and then register it with our app

@users.route('/register',methods=['GET','POST'])
def register():
    #if user is alread logged in
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    #create instance of our form that we're going to send to our app
    form = RegisterationForm()
    #validate form submit method
    #flash msg-->easy way to send a one time alert 
    if form.validate_on_submit():
        # To hash the pswd entered by the user
        hashed_pswd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # now we create a new user
        user = User(username = form.username.data,email=form.email.data,password=hashed_pswd)
        # Now add this user to the changes we want to make in our db
        db.session.add(user)
        db.session.commit()
        #display a msg when we have created a user successfully
        #older way:
        #flash(f"Account created for {form.username.data}!",'success')#categories=success,warning,danger
        #newer way:
        flash("Account created for successfully!",'success')
        return redirect(url_for('users.login'))
    #pass this form to a template
    return render_template('register.html',title='Register',form=form)


@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        #older--->
        # if form.email.data=='admin@blog.com' and form.password.data == 'password':
        #     flash("Successfully Logged In!",'success')
        #     return redirect(url_for('main.home'))
        # else:
        #     flash("Login Unsuccessful! Please check username and password.",'danger')
        #     #return redirect(url_for('users.login'))
        #newer--->
        #make sure the user exists:
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user,remember=form.remember.data)
            # if there is a next keyword in thje url it redirects to that url
            next_page = request.args.get('next')
            if(next_page):
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))
        else:
            flash("Login Unsuccessful! Please check email and password.",'danger')
    return render_template('login.html',title='Login',form=form)


@users.route("/logout")
def logout():
    logout_user() 
    return redirect(url_for('main.home'))

#how to put certain restrictions on some routes so that you go to them only if you are logged in--->i.e. login before you can view that page
@users.route("/account",methods=['GET','POST'])
@login_required #--you need to login to access this route
def account():
    form = UpdateAccountForm()
    # if our form is valid then we can update our username and email
    if form.validate_on_submit():
        #check if there is any picture data
        if form.picture.data:
            #set the users profile pic
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        #to update:-->when updated the old values will no longer be in the db
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        #flash msg that tells the user that acc has been updtaed
        flash('Your account has been updated!','success')
        return redirect(url_for('users.account'))
    # for the form to display the current username and address when we visit the account
    elif request.method =='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    #tell where our login route is located?-->init--->login_manager.login_view = 'login'
    #set img file to be passed to the account template
    image_file = url_for('static',filename='profile_pics/' + current_user.image_file)
    return render_template('account.html',title='Account',image_file=image_file,form=form)


#display the posts of inly that user whose username is clicked on
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)#default page no is 1 
    #query for the particular user and then grab their posts
    user = User.query.filter_by(username=username).first_or_404()
    post = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page = page,per_page=5)
    return render_template('user_posts.html',posts=post,user=user)


@users.route("/reset_password",methods=['GET','POST'])
#user will have to be logged out to access this
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RequestResetForm()
    # if form was validated and submitted
    if form.validate_on_submit():
        user =User.query.filter_by(email=form.email.data).first()
        #send email to the user with the token to reset pswd-->send_reset_email fn is used
        send_reset_email(user)
        flash('An email has been sent to reset your password','info')#email is sent using flask_mail in __init__.py
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title='Reset Password',form=form)

#route where user actually resets their pswd:
@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_token(token):
    #we have to make sure that its the actual user and the token we gave them in the email is active and we get the token from the url
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    #if invalid token:
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form=ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pswd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_pswd 
        db.session.commit()
        flash("Your password has been updated successfully!",'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title='Reset Password',form=form)
    
#add a link to the reset password page to our application

flaskblog_3/flask_webapp/templates/about.html
<!-- child template -->
{% extends "layout.html" %}
{% block content %}
    <h1>Hey Bloggers!!</h1>
    <p>Welcome to the one stop for all the keen thinkers out their.</p>
{% endblock content %}

flaskblog_3/flask_webapp/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <!--<h1>{{ current_user.username }}</h1> ---older -->
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
      <!--FORM HERE--to be able to update or edit username,email address,profile pic-->
        <form method="POST" action="" enctype="multipart/form-data"> <!--special encoding type for our form to pass our image data properly-->
        <!--when we post this form its going to go back to the same route i.e. post
        that info to the same route that we are currently on-->
            <!-- form.hidden_tag()--it adds a CSRF i.e. a cross-site request forgery token-->
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Details</legend>
                <!--create form groups using div to use form fields-->
                <div class=" form-group">
                     {{ form.username.label(class="form-control-label") }}
                     <!--print errors if user inputs invalid data/info-->
                     {% if form.username.errors %}
                        {{ form.username(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                     {% else %}
                        {{ form.username(class="form-control form-contol-lg") }}<!--lg for large here-->
                     {% endif %}  
                </div>
                <div class=" form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                     {% else %}
                        {{ form.email(class="form-control form-contol-lg") }}<!--lg for large here-->
                     {% endif %} 
                </div>
                <div class=" form-group">
                  {{ form.picture.label() }}
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                      <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                  {% endif %}
                </div>
            </fieldset>
            <div class=" form-group">
                {{ form.submit(class="btn btn-outline-info") }}
           </div>
        </form>
    </div>
{% endblock content %}

flaskblog_3/flask_webapp/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
        <!--when we post this form its going to go back to the same route i.e. post
        that info to the same route that we are currently on-->
            <!-- form.hidden_tag()--it adds a CSRF i.e. a cross-site request forgery token-->
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <!--create form groups using div to use form fields-->
                <div class=" form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                    {% else %}
                        {{ form.title(class="form-control form-contol-lg") }}<!--lg for large here-->
                    {% endif %} 
                </div>
                <div class=" form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                    {% else %}
                        {{ form.content(class="form-control form-contol-lg") }}
                    {% endif %} 
                </div>
            </fieldset>
            <div class=" form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog_3/flask_webapp/templates/home.html
<!-- child template -->
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <!--<h1>{{ post.title }}</h1>
        <p>By {{post.author}} on {{post.date_posted}}</p>
        <p>{{post.content}}</p>#older-->
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="text-info mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}" >{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div> 
        </article>
    {% endfor %} 
    <!--create links to the pages at the bottom of each page-->
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_num %}
            {% if posts.page==page_num %}
                <a class="btn btn-light mb-4" href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-light mb-4" href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog_3/flask_webapp/templates/layout.html
<!-- parent template -->
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS --> <!-- starter template from bootstrap 4 site -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- css file from static folder  -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css') }}">

    {% if title%}
        <title>Blog - {{title}}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>    
<body>
    <!-- Navigation bar from webdev code snippets folder -->
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                <!-- jinja2 condition to check if user is already logged in or not -->
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                  {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>

    <main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}<!--get_flashed_messages function gets the flashed messages sent to this template-->
            {% if messages %}<!--if there is a msg it will get printed-->
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
        <div class="content-section">
            <h3>What's New?</h3>
            <p class='text-muted'>Browse the latest posts:
            <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a class="text-info" href="{{ url_for('main.home') }}">Latest Posts</a></li></li>
                <li class="list-group-item list-group-item-light"><a class="text-info" href="{{ url_for('main.home') }}">Most Popular Posts</a></li>
                <li class="list-group-item list-group-item-light"><a class="text-info" href="{{ url_for('users.account') }}">New Messages</a></li>
            </ul>
            </p>
        </div>
        </div>
    </div>
    </main>
    <!-- Footer -->
    
    <footer class="page-footer mt-auto">
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3" style="color:#112d32">© 2021 Copyright:
        Built by <a href="https://www.linkedin.com/in/tanisha-garg-8b417a171" style="color:#00003b">Tanisha Garg</a>
      </div>
      <!-- Copyright -->
    </footer>
    
    <!-- Footer -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog_3/flask_webapp/templates/login.html
<!-- child template  we have to put our form in the content section -->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
        <!--when we post this form its going to go back to the same route i.e. post
        that info to the same route that we are currently on-->
            <!-- form.hidden_tag()--it adds a CSRF i.e. a cross-site request forgery token-->
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login to your Account</legend>
                <!--create form groups using div to use form fields-->
                <div class=" form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                     {% else %}
                        {{ form.email(class="form-control form-contol-lg") }}<!--lg for large here-->
                     {% endif %} 
                </div>
                <div class=" form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                     {% else %}
                        {{ form.password(class="form-control form-contol-lg") }}
                     {% endif %} 
                </div>
                <!--add a remember me checkbox-->
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class=" form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <!--add a forgot password field-->
                <small class="text-muted ml-2">
                    <a class="text-dark" href="{{url_for('users.reset_request')}}">Forgot your Password?</a>
                </small>
           </div>
        </form>
    </div>
    <div class="border-top pt-0">
        <small class="text-muted"><!--text-muted fades out the text a bit-->
            Need an account?<a class=" text-dark ml-1" href="{{url_for('users.register')}}">Register Here</a>
        </small>
    </div>
{% endblock content %}

flaskblog_3/flask_webapp/templates/post.html
<!--single post template-->
<!-- child template -->
{% extends "layout.html" %}
{% block content %}
    <!--<h1>{{ post.title }}</h1>
    <p>By {{post.author}} on {{post.date_posted}}</p>
    <p>{{post.content}}</p>#older-->
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class= "btn btn-secondary btn-sm mt-1 mb-1"href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        <!--bootstrap website--modal--live demo section-->
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Do you want to Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

flaskblog_3/flask_webapp/templates/reset_request.html
<!-- child template  similar to login.html template -->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <!--create form groups using div to use form fields-->
                <div class=" form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-contol-lg, is-invalid") }}  
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div> 
                     {% else %}
                        {{ form.email(class="form-control form-contol-lg") }}<!--lg for large here-->
                     {% endif %} 
                </div>
            </fieldset>
            <div class=" form-group">
                {{ form.submit(class="btn btn-outline-info") }}
           </div>
        </form>
    </div>
{% endblock content %}

flaskblog_3/flask_webapp/templates/user_posts.html
<!-- child template/similar to home.html -->
{% extends "layout.html" %}
{% block content %}
    <!--specify which users posts areshown by this page-->
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+post.author.image_file) }}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="text-info mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div> 
        </article>
    {% endfor %} 
    <!--create links to the pages at the bottom of each page-->
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_num %}
            {% if posts.page==page_num %}
                <a class="btn btn-light mb-4" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-light mb-4" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}